name: Keep repository alive

on:
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC，按需调整
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "chore(keep-alive): daily empty commit [skip ci]"

      - name: Push commit
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          git push origin "HEAD:${BRANCH}"
